=== pgreen14/HospitalSchedulingSystem/BTE324Final/resources/scheduling.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://SCHEDULER"
targetNamespace="http://SCHEDULER"
   elementFormDefault="qualified">
    
    <element name="schedulerList">
    	<complexType>
    		<sequence>
    			<element name="patient" type="tns:Patient"
    				maxOccurs="unbounded" minOccurs="0">
    			</element>
    			<element name="doctor" type="tns:Doctor"
    				maxOccurs="unbounded" minOccurs="0">
    			</element>
    			<element name="visit" type="tns:Visit" maxOccurs="unbounded" minOccurs="0"></element>
    		</sequence>
    	</complexType>
    </element>



    <simpleType name="MedicalSpecialty">
    	<restriction base="string">
    		<enumeration value="GENERAL_MEDICINE"></enumeration>
    		<enumeration value="PEDIATRICS"></enumeration>
    		<enumeration value="ONCOLOGY"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="Patient">
    	<sequence>
            <element name="name" type="tns:Name"></element>
            
            <element name="email" type="string"></element>
            <element name="dob" type="date"></element>
    	</sequence>
    	<attribute name="patientID" type="int"></attribute>
    	<attribute name="ssn" type="string"></attribute>
    </complexType>






    <complexType name="Visit">
    	<attribute name="patientID" type="int"></attribute>
    	<attribute name="doctorID" type="int"></attribute>
    	<attribute name="visitDate" type="date"></attribute>
    </complexType>




    <complexType name="Name">
    	<sequence>
    		<element name="fname" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="lname" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>


    <complexType name="Doctor">
    	<sequence>
    		<element name="name" type="tns:Name" minOccurs="0" maxOccurs="1"></element>
    		<element name="email" type="string"></element>
    		<element name="dob" type="date"></element>
    		<element name="specialty" type="tns:MedicalSpecialty"></element>
    	</sequence>
    	<attribute name="doctorID" type="int"></attribute>
    	<attribute name="ssn" type="string"></attribute>
    </complexType>
</schema>

=== pgreen14/HospitalSchedulingSystem/BTE324Final/resources/schedulerDataIn.xml
<?xml version="1.0" encoding="UTF-8"?>
<schedulerList xmlns="http://SCHEDULER" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xsi:schemaLocation="http://SCHEDULER scheduling.xsd"
>
	<patient patientID="0" ssn="123-45-6789">
		<name>
			<fname>John</fname>
			<lname>Lennon</lname>
		</name>
		<email>jlennon@beatles.com</email>
		<dob>1951-05-01</dob>
	</patient>
	<doctor>
		<name>
			<fname>fname</fname>
			<lname>lname</lname></name>
		<email>email</email>
		<dob>2001-01-01</dob>
		<specialty>GENERAL_MEDICINE</specialty>
	</doctor>
	<visit patientID="0" doctorID="0" visitDate="2017-05-11" /></schedulerList>
